import type { Metadata } from 'next';
import 'src/styles/globals.scss';
import localFont from 'next/font/local';

const helveticaReg = localFont({
  src: [
    {
      path: '../../public/assets/fonts/HelveticaRegular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica-regular',
});

const helveticaMed = localFont({
  src: [
    {
      path: '../../public/assets/fonts/HelveticaMedium.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica-medium',
});

export const metadata: Metadata = {
  title: 'Cities',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${helveticaReg.variable} ${helveticaMed.variable}`}>{children}</body>
    </html>
  );
}
